import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://gcef.sorocaba.sp.gov.br/")
    page.get_by_role("main").get_by_role("link", name=" Entrar").click()
    page.get_by_role("button", name=" Continuar").dblclick()
    page.get_by_role("textbox", name="Nome de usuário").fill("jecampos")
    page.get_by_role("textbox", name="Nome de usuário").press("Tab")
    page.get_by_role("textbox", name="Senha").fill("W@sh@skos@6669244")
    page.get_by_role("button", name="Entrar").click()
    page.get_by_role("link", name=" Enviar Certificados").first.click()
    page.get_by_role("textbox", name="Nome do curso").click()
    page.get_by_role("textbox", name="Nome do curso").fill("NOME 01")
    page.get_by_role("textbox", name="Nome do curso").press("Tab")
    page.get_by_role("textbox", name="Instituição").fill("INSTITUIÇÃO 01")
    page.get_by_role("textbox", name="Instituição").press("Tab")
    page.locator("#id_form-0-classificacao").press("Tab")
    page.locator("#id_form-0-tipo").press("Tab")
    page.get_by_placeholder("Horas").fill("10")
    page.get_by_placeholder("Horas").press("Tab")
    page.get_by_placeholder("Min").press("Tab")
    page.get_by_role("button", name="Choose File").click()
    page.get_by_role("button", name="Choose File").set_input_files("000_postgresql_triggers_transacoes_erros_cursores.pdf")
    page.locator("#id_form-0-data_inicio").fill("2025-12-18")
    page.locator("#id_form-0-data_inicio").press("Tab")
    page.locator("#id_form-0-data_inicio").press("Tab")
    page.locator("#id_form-0-data_fim").press("Home")
    page.locator("#id_form-0-data_fim").press("ArrowLeft")
    page.locator("#id_form-0-data_fim").press("ArrowLeft")
    page.locator("#id_form-0-data_fim").press("ArrowLeft")
    page.locator("#id_form-0-data_fim").fill("2025-12-31")
    page.locator("#id_form-0-data_emissao").press("Home")
    page.locator("#id_form-0-data_emissao").press("ArrowLeft")
    page.locator("#id_form-0-data_emissao").press("ArrowLeft")
    page.locator("#id_form-0-data_emissao").fill("2026-04-11")
    page.get_by_role("button", name=" Adicionar Certificado").click()
    page.locator("#id_form-1-certificacao").click()
    page.locator("#id_form-1-certificacao").fill("CURSO 02 ")
    page.locator("#id_form-1-certificacao").press("Tab")
    page.locator("#id_form-1-instituicao").fill("INSTITUIÇÃO 02")
    page.locator("#id_form-1-classificacao").select_option("35")
    page.get_by_text("Escola Gestão Pública = horas").nth(1).click()
    page.locator("#id_form-1-tipo").select_option("4")
    page.locator("#id_form-1-carga_horaria_0").click()
    page.locator("#id_form-1-carga_horaria_0").fill("50")
    page.locator("#id_form-1-carga_horaria_1").click()
    page.locator("#id_form-1-carga_horaria_1").fill("00")
    page.locator("#id_form-1-certificado").click()
    page.locator("#id_form-1-certificado").set_input_files("001_pep8_linters_python.pdf")
    page.locator("#id_form-1-data_inicio").fill("2025-11-15")
    page.locator("#id_form-1-data_fim").fill("2025-11-22")
    page.locator("#id_form-1-data_emissao").press("ArrowLeft")
    page.locator("#id_form-1-data_emissao").press("ArrowLeft")
    page.locator("#id_form-1-data_emissao").fill("2026-04-11")
    page.get_by_role("button", name=" Adicionar Certificado").click()
    page.get_by_role("button", name=" Adicionar Certificado").click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
